config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  # get 'websites/index'
  # get 'websites/show'
  # get 'articles/index'
  # get 'articles/show'
  devise_for :users
  root to: 'pages#home'
  # root to: "websites#index" ??

  resources :users, only: [:show, :edit, :update]

  resources :websites, only: [:index, :show, :update] do
    resources :articles, only: [:index, :show, :create]
    # nest with article show?
    # no article create?
  end

  # no article actions?
  resources :articles, only: [:index, :show, :create, :update] do
    resources :likes, only: [:create, :destroy]
  end

  resources :articles, only: [:index, :show, :create, :update] do
    resources :favorites, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  has_many :favorites
  has_many :likes
  has_many :favorited_articles, through: :favorites, source: :article
  has_many :liked_articles, through: :likes, source: :article
  def already_liked?(article)
    self.likes.exists?(article_id: article.id)
  end
  has_one_attached :photo
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    @user.save
    # Cloudinary
  end

  private

  def user_params
    params.require(:user).permit(:name, :photo)
  end
end

# test memo

app/views/users/edit.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>Your dashboard</h1>
<!-- <h3><%= @user.email %></h3>
<h2>投稿内容</h2> -->
<%# @user.like_articles.each do |article| %>
  <!--   <a href="/articles/<%#= article.id %>"><%#= article.content %></a>
  <hr> -->
  <%# end %>
  <h3>The articles you liked</h3>
  <% @user.liked_articles.each do |article| %>
    <div class="card-product">
      <%= image_tag article.image, alt: "article image", class: "card-product-image" %>
      <!-- <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" /> -->
      <div class="card-product-infos">
        <!-- <h2><%#= link_to article.name, website_article_path(@website, article) %></h2> -->
        <h2><%= link_to article.name, article.url, target: :_blank %></h2>
        <p><%= article.summary %></p>
      </div>
    </div>
  <% end %>
  <%#= link_to "ユーザー一覧へ", users_path %>
  <%= link_to "Search other articles", root_path %>